Models/ErrorViewModel.cs
namespace Fetch_API.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PersonModel.cs
namespace Fetch_API.Models
{
    public class PersonModel
    {
        public int PersonID { get; set; }
        public string Name { get; set; }
        public string? Contact { get; set; }
        public string? Email { get; set; }
    }
    public class PersonModel2
    {
        public string Name { get; set; }
        public string? Contact { get; set; }
        public string? Email { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fetch_API.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/PersonController.cs
using Fetch_API.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace Fetch_API.Controllers
{
    public class PersonController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        Uri baseAddress = new Uri("http://localhost:5186/api/Person");
        private readonly HttpClient _httpClient;

        public PersonController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }

        #region GetAll

        [HttpGet]
        public IActionResult Get()
        {
            List<PersonModel> persons = new List<PersonModel>();
            HttpResponseMessage response = _httpClient.GetAsync(baseAddress).Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;

                dynamic jsonobject = JsonConvert.DeserializeObject(data);

                var dataOfObject = jsonobject.data;
                var extractDataJson = JsonConvert.SerializeObject(dataOfObject);

                persons = JsonConvert.DeserializeObject<List<PersonModel>>(extractDataJson);
            }
            return View("PersonList", persons);
        }

        #endregion

        #region Add / Edit

        [HttpGet]
        public IActionResult Edit(int PersonID)
        {
            PersonModel persons = new PersonModel();

            Console.WriteLine(_httpClient.BaseAddress);
            HttpResponseMessage response = _httpClient.GetAsync($"{_httpClient.BaseAddress}/{PersonID}").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;

                dynamic jsonobject = JsonConvert.DeserializeObject(data);

                var dataOfObject = jsonobject.data;
                var extractDataJson = JsonConvert.SerializeObject(dataOfObject, Formatting.Indented);

                persons = JsonConvert.DeserializeObject<PersonModel>(extractDataJson);
            }
            return View("Create", persons);



        }

        [HttpPost]
        public async Task<IActionResult> Save(PersonModel model)
        {
            try
            {
                MultipartFormDataContent formData = new MultipartFormDataContent();
                formData.Add(new StringContent(model.Name), "Name");
                formData.Add(new StringContent(model.Contact), "Contact");
                formData.Add(new StringContent(model.Email), "Email");

                if (model.PersonID == 0)
                {
                    HttpResponseMessage res = await _httpClient.PostAsync($"{_httpClient.BaseAddress}", formData);
                    if (res.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Data Added Successfully.";
                        return RedirectToAction("Get");
                    }

                }
                else
                {
                    HttpResponseMessage res = await _httpClient.PutAsync($"{_httpClient.BaseAddress}/{model.PersonID}", formData);
                    if (res.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Data Updated Successfully.";
                        return RedirectToAction("Get");
                    }
                }
                return View("Create");
            }
            catch (Exception e)
            {
                TempData["Message"] = e.Message;

            }

            return View("PersonList");
        }

        #endregion

        #region Delete

        [HttpGet("{PersonID}")]
        public IActionResult Delete(int PersonID)
        {
            HttpResponseMessage response = _httpClient.DeleteAsync($"{_httpClient.BaseAddress}/{PersonID}").Result;
            Console.WriteLine(PersonID);
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Person Deleted successfully...!!!";
            }
            return RedirectToAction("Get");
        }

        #endregion


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Person/Create.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model Fetch_API.Models.PersonModel

<div class="row">
    <div class="col-md-4">
        <form asp-action="Save" asp-controller="Person">
            @Html.HiddenFor(x=>x.PersonID)
            @*<div class="form-group">
            <label asp-for="PersonID" class="control-label"></label>
            <input asp-for="PersonID" class="form-control" />
            <span asp-validation-for="PersonID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="PersonID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="PersonID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="PersonID" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input class="btn btn-success" type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
                }

Views/Person/PersonList.cshtml
@model IEnumerable<Fetch_API.Models.PersonModel>

<div>
    <h5>@TempData["Message"]</h5>
</div>


<div>
    <a asp-action="Edit" asp-controller="Person">
        Add new Person
    </a>
</div>

<table>
    <tr>
        <th>Person ID</th>
        <th>Name</th>
        <th>Email ID</th>
        <th>Contact</th>
        <th>Actions</th>
    </tr>
    @foreach(var i in Model)
    {
       <tr>
           <td>@i.PersonID</td>
            <td>@i.Name</td>
            <td>@i.Email</td>
            <td>@i.Contact</td>
            <td>
                <a class="btn btn-primary" href="@Url.Action("Edit","Person",new{PersonID=i.PersonID})">Edit</a>
                <a class="btn btn-danger" href="@Url.Action("Delete","Person",new{PersonID=i.PersonID})">Delete</a>

            </td>
       </tr> 
    }
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fetch_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fetch_API.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fetch_API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Get">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                var errorMessage = TempData["ErrorMessage"]?.ToString();
                var successMessage = TempData["SuccessMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(successMessage))
            {
                <div class="alert alert-success">
                    <b>Success : </b>@successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if (!string.IsNullOrWhiteSpace(errorMessage))
            {
                <div class="alert alert-success">
                    <b>Error : </b>@errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fetch_API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>